#!/bin/sh
set -ex
ZUUL_CLONER=/usr/zuul-env/bin/zuul-cloner

if $(python -c "import ironic" 2> /dev/null); then
    echo "Ironic already installed."
elif [ -x $ZUUL_CLONER ]; then
    $ZUUL_CLONER --cache-dir /opt/git --workspace /tmp git://git.openstack.org openstack/ironic
    pip install /tmp/openstack/ironic
else
    wget -N http://tarballs.openstack.org/ironic/ironic-master.tar.gz
    pip install ironic-master.tar.gz
fi

pip install -U $*

exit $?
